# Generated by Django 5.2.5 on 2025-08-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comics/'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
